# Generated by Django 3.2.17 on 2023-02-10 20:19

import albums.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Название альбома')),
                ('year', models.PositiveIntegerField(validators=[albums.models.year_validator], verbose_name='Год выхода')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Sing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Название песни')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Название исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='AlbumSing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sing', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер песни в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('sing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.sing', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Связь альбома и песни',
                'ordering': ('album',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.singer', verbose_name='Исполнитель альбома'),
        ),
        migrations.AddField(
            model_name='album',
            name='sings',
            field=models.ManyToManyField(through='albums.AlbumSing', to='albums.Sing'),
        ),
        migrations.AddConstraint(
            model_name='albumsing',
            constraint=models.UniqueConstraint(fields=('album', 'sing', 'number_sing'), name='unique sing in album'),
        ),
    ]
