# Generated by Django 3.2.17 on 2023-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sings',
            field=models.ManyToManyField(related_name='albums', through='albums.AlbumSing', to='albums.Sing'),
        ),
    ]
