# Generated by Django 3.2.17 on 2023-02-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_sings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=48, unique=True, verbose_name='Название исполнителя'),
        ),
    ]
