# Generated by Django 3.2.17 on 2023-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_singer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumsing',
            options={'ordering': ('album',), 'verbose_name': 'Связь альбома и песни', 'verbose_name_plural': 'Связи альбомов и песен'},
        ),
        migrations.RemoveConstraint(
            model_name='albumsing',
            name='unique sing in album',
        ),
        migrations.AddConstraint(
            model_name='albumsing',
            constraint=models.UniqueConstraint(fields=('album', 'sing'), name='unique sing in album'),
        ),
        migrations.AddConstraint(
            model_name='albumsing',
            constraint=models.UniqueConstraint(fields=('album', 'number_sing'), name='unique number_sing in album'),
        ),
    ]
