# Generated by Django 3.2.17 on 2023-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20230212_1646'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'year', 'singer'), name='unique name year singer in album'),
        ),
    ]
