# Generated by Django 3.2.17 on 2023-02-13 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_unique name year singer in album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsing',
            name='number_sing',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер песни в альбоме'),
        ),
    ]
